### ISSUE TITLE
Remove --full flag

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/cocoapods-search#13]
After the improvements in #8 merged completely, I think we can get rid of `--full` flag because it would give answer in less than a second in most cases.

**Comment by manuyavuz** [comment]
@orta We thought about removing --full flag, but I have a small concern.

non-git repositories still won't utilize improvements presented. Their search will still be slow.

However, I do think we can still move --full as default option because I assume users using non-git repos will be much minority.

What about adding a new flag like `--simple` and moving `--full` algorithm to default option?

cc: @alloy @floere @segiddins

**Comment by segiddins** [comment]
Sounds good to me!

**Comment by orta** [comment]
Yeah, that's cool for me too

**Comment by manuyavuz** [comment]
Good then.
