### ISSUE TITLE
Print found pods using `less` command

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/cocoapods-search#17]
I think this will really help with printing results of search queries.

Currently, when you try `pod search a`, just printing found pods takes 20 secs. With `pod search --simple a`, it takes 16 secs.

Current way really does not fit well. We should find a way to print only first parts, and let user continue with input.

I thought about using the following:

``` ruby
IO.popen('less', 'w') do |io|
  io.puts('blah blah')
end
```

However,  it currently is not possible because search prints pods using `UI.pod` method, which calls puts internally.

Do you have any suggestions how should/could I integrate this, @orta, @floere, @segiddins?

**Comment by segiddins** [comment]
Should be possible to redirect output to a pager, even by reopening the STDOUT IO, but I don't know exactly how.

**Comment by kylef** [comment]
I was thinking the same, but please respect the `PAGER` env variable.
