### ISSUE TITLE
Integrate back into CocoaPods

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods-search#3]
- [x] Create a CHANGELOG in the search plugin (this version is just extracted from CocoaPods).
- [x] Add `cocoapods-search` to Rainforest: https://github.com/CocoaPods/Rainforest/blob/master/Rakefile#L20 (via pull request)
- [x] Create a pull request into CocoaPods to add the plugin and remove existing search code
  - [x] Add to `cocoapods-search` to [gemspec](https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec#L37) then bundle install
  - [x] Remove existing source code related to search

**Comment by emkosz** [comment]
Done!
